import type {
  Expense,
  FinanceData,
  Income,
  Installment,
  Investment,
  InvestmentKind,
  Liability,
  Member,
  MemberScope,
  Policy,
  PremiumFrequency,
} from './types';
import { addMonthsToDate, addMonthsToKey, dateInMonth, daysBetween, toMonthKey } from './dates';

// ---------------------------------------------------------------------------
// EMI maths
// ---------------------------------------------------------------------------

/**
 * Standard reducing-balance EMI: P·r·(1+r)^n / ((1+r)^n − 1), r = monthly rate.
 * A 0% rate (no-cost EMI) splits the principal evenly. Rounded to the rupee.
 */
export function calculateEmi(principal: number, annualRatePct: number, months: number): number {
  if (principal <= 0 || months <= 0) return 0;
  const r = annualRatePct / 12 / 100;
  if (r === 0) return Math.round(principal / months);
  const f = Math.pow(1 + r, months);
  return Math.round((principal * r * f) / (f - 1));
}

export function emiBreakdown(principal: number, annualRatePct: number, months: number) {
  const emi = calculateEmi(principal, annualRatePct, months);
  const totalPayable = emi * months;
  return { emi, totalPayable, totalInterest: Math.max(0, totalPayable - principal) };
}

/** Month-by-month installments for a plan. Ids are generated by `makeId`. */
export function buildInstallments(
  liabilityId: string,
  emiAmount: number,
  tenureMonths: number,
  startMonth: string,
  makeId: () => string,
): Installment[] {
  return Array.from({ length: tenureMonths }, (_, i) => ({
    id: makeId(),
    liabilityId,
    seq: i + 1,
    dueMonth: addMonthsToKey(startMonth, i),
    amount: emiAmount,
  }));
}

export function hasPlan(l: Pick<Liability, 'emiAmount' | 'tenureMonths'>): boolean {
  return Boolean(l.emiAmount && l.emiAmount > 0 && l.tenureMonths && l.tenureMonths > 0);
}

// ---------------------------------------------------------------------------
// Per-liability figures
// ---------------------------------------------------------------------------

export interface PlanProgress {
  paidCount: number;
  totalCount: number;
  paidAmount: number;
  remainingAmount: number;
  percent: number;
  nextDue?: Installment;
  lastMonth?: string;
}

export function planProgress(installments: Installment[]): PlanProgress {
  let paidCount = 0;
  let paidAmount = 0;
  let remainingAmount = 0;
  let nextDue: Installment | undefined;
  for (const i of installments) {
    if (i.paidOn) {
      paidCount++;
      paidAmount += i.amount;
    } else {
      remainingAmount += i.amount;
      if (!nextDue || i.seq < nextDue.seq) nextDue = i;
    }
  }
  const totalCount = installments.length;
  return {
    paidCount,
    totalCount,
    paidAmount,
    remainingAmount,
    percent: totalCount ? Math.round((paidCount / totalCount) * 100) : 0,
    nextDue,
    lastMonth: installments.reduce<string | undefined>((m, i) => (!m || i.dueMonth > m ? i.dueMonth : m), undefined),
  };
}

/** What is still owed: unpaid installments for a plan, otherwise the balance. Closed = 0. */
export function outstandingFor(l: Liability, installments: Installment[]): number {
  if (l.status === 'closed') return 0;
  if (installments.length > 0) return planProgress(installments).remainingAmount;
  return l.balance;
}

export function groupInstallments(installments: Installment[]): Map<string, Installment[]> {
  const map = new Map<string, Installment[]>();
  for (const i of installments) {
    const list = map.get(i.liabilityId);
    if (list) list.push(i);
    else map.set(i.liabilityId, [i]);
  }
  for (const list of map.values()) list.sort((a, b) => a.seq - b.seq);
  return map;
}

// ---------------------------------------------------------------------------
// Scope filtering
// ---------------------------------------------------------------------------

export function scopeData(data: FinanceData, scope: MemberScope): FinanceData {
  if (scope === 'all') return data;
  const liabilities = data.liabilities.filter((l) => l.memberId === scope);
  const ids = new Set(liabilities.map((l) => l.id));
  return {
    members: data.members.filter((m) => m.id === scope),
    liabilities,
    installments: data.installments.filter((i) => ids.has(i.liabilityId)),
    expenses: data.expenses.filter((e) => e.memberId === scope),
    policies: data.policies.filter((p) => p.memberId === scope),
    incomes: data.incomes.filter((x) => x.memberId === scope),
    investments: data.investments.filter((x) => x.memberId === scope),
  };
}

// ---------------------------------------------------------------------------
// Income
// ---------------------------------------------------------------------------

/** Take-home income spread per month. Inactive sources count as 0. */
export function monthlyIncome(i: Income): number {
  return i.isActive ? (i.amount * PAYMENTS_PER_YEAR[i.frequency]) / 12 : 0;
}

export function totalMonthlyIncome(incomes: Income[]): number {
  return Math.round(incomes.reduce((s, i) => s + monthlyIncome(i), 0));
}

// ---------------------------------------------------------------------------
// Investments
// ---------------------------------------------------------------------------

/** Kinds paid in instalments every month/quarter. */
export const RECURRING_INVESTMENTS: InvestmentKind[] = ['sip', 'rd', 'ppf', 'epf', 'nps'];
/** Kinds where the amount entered is today's balance (PPF passbook, EPF statement, bank balance), not money put in at the start. */
export const BALANCE_KINDS: InvestmentKind[] = ['ppf', 'epf', 'savings'];
/** Kinds whose value follows the market — growth is only known if the user enters a current value. */
export const MARKET_LINKED: InvestmentKind[] = ['sip', 'mutual_fund', 'stocks', 'nps', 'gold'];

function monthsElapsed(fromIso: string, toIso: string): number {
  const [fy, fm, fd] = fromIso.split('-').map(Number);
  const [ty, tm, td] = toIso.split('-').map(Number);
  return Math.max(0, (ty - fy) * 12 + (tm - fm) - (td < fd ? 1 : 0));
}

/** Instalments paid so far for a recurring plan (counting the first one on the start date). */
function contributionsSoFar(inv: Investment, todayIso: string): number {
  if (!inv.contribution || !inv.startDate || inv.startDate > todayIso) return 0;
  const step = MONTHS_BETWEEN_PREMIUMS[inv.frequency ?? 'monthly'];
  const end = inv.maturityDate && inv.maturityDate < todayIso ? inv.maturityDate : todayIso;
  return Math.floor(monthsElapsed(inv.startDate, end) / step) + 1;
}

/** Money put in so far: what the user entered, or contributions estimated from the start date. */
export function investedSoFar(inv: Investment, todayIso: string): number {
  if (inv.invested > 0) return inv.invested;
  return (inv.contribution ?? 0) * contributionsSoFar(inv, todayIso);
}

/** Indian bank deposits compound quarterly. */
const fdGrowth = (principal: number, ratePct: number, months: number) => principal * Math.pow(1 + ratePct / 400, (4 * months) / 12);

/**
 * Today's value: the figure the user entered, else interest accrued for
 * fixed-income kinds (FD, RD, PPF, EPF, savings), else what was put in.
 */
export function currentValue(inv: Investment, todayIso: string): number {
  if (inv.status === 'closed') return 0;
  if (inv.currentValue !== undefined && inv.currentValue > 0) return inv.currentValue;
  if (BALANCE_KINDS.includes(inv.kind) && inv.invested > 0) return inv.invested;
  const principal = investedSoFar(inv, todayIso);
  const rate = inv.interestRate ?? 0;
  if (!rate || !inv.startDate || MARKET_LINKED.includes(inv.kind)) return principal;
  const end = inv.maturityDate && inv.maturityDate < todayIso ? inv.maturityDate : todayIso;
  if (RECURRING_INVESTMENTS.includes(inv.kind) && inv.contribution && inv.invested <= 0) {
    // Each instalment grows from the month it was paid
    const step = MONTHS_BETWEEN_PREMIUMS[inv.frequency ?? 'monthly'];
    const n = contributionsSoFar(inv, todayIso);
    const total = monthsElapsed(inv.startDate, end);
    let value = 0;
    for (let k = 0; k < n; k++) value += fdGrowth(inv.contribution, rate, Math.max(0, total - k * step));
    return Math.round(value);
  }
  return Math.round(fdGrowth(principal, rate, monthsElapsed(inv.startDate, end)));
}

/** Projected value at maturity for FD/RD-style deposits; undefined when it can't be known. */
export function maturityValue(inv: Investment, todayIso: string): number | undefined {
  if (!inv.maturityDate || !inv.startDate || !inv.interestRate || MARKET_LINKED.includes(inv.kind)) return undefined;
  if (inv.maturityDate <= todayIso) return currentValue(inv, todayIso);
  if (BALANCE_KINDS.includes(inv.kind) && inv.invested > 0) {
    // Today's balance grows to maturity, plus any instalments still to come
    const ahead = monthsElapsed(todayIso, inv.maturityDate);
    let value = fdGrowth(inv.invested, inv.interestRate, ahead);
    if (inv.contribution && inv.status === 'active') {
      const step = MONTHS_BETWEEN_PREMIUMS[inv.frequency ?? 'monthly'];
      for (let k = step; k <= ahead; k += step) value += fdGrowth(inv.contribution, inv.interestRate, ahead - k);
    }
    return Math.round(value);
  }
  const months = monthsElapsed(inv.startDate, inv.maturityDate);
  if (RECURRING_INVESTMENTS.includes(inv.kind) && inv.contribution) {
    const step = MONTHS_BETWEEN_PREMIUMS[inv.frequency ?? 'monthly'];
    let value = 0;
    for (let k = 0; k * step < months; k++) value += fdGrowth(inv.contribution, inv.interestRate, months - k * step);
    return Math.round(value);
  }
  return Math.round(fdGrowth(inv.invested, inv.interestRate, months));
}

/** Recurring contribution spread per month (active plans only). */
export function monthlyContribution(inv: Investment): number {
  if (inv.status !== 'active' || !inv.contribution) return 0;
  return inv.contribution / MONTHS_BETWEEN_PREMIUMS[inv.frequency ?? 'monthly'];
}

export interface PortfolioSummary {
  invested: number;
  value: number;
  gain: number;
  gainPct: number;
  monthlyContributions: number;
  emergencyFund: number;
  byKind: { kind: InvestmentKind; value: number }[];
}

export function portfolioSummary(investments: Investment[], todayIso: string): PortfolioSummary {
  let invested = 0;
  let value = 0;
  let monthly = 0;
  let emergencyFund = 0;
  const byKind = new Map<InvestmentKind, number>();
  for (const inv of investments) {
    if (inv.status === 'closed') continue;
    const put = investedSoFar(inv, todayIso);
    const now = currentValue(inv, todayIso);
    invested += put;
    value += now;
    monthly += monthlyContribution(inv);
    if (inv.emergencyFund) emergencyFund += now;
    byKind.set(inv.kind, (byKind.get(inv.kind) ?? 0) + now);
  }
  return {
    invested: Math.round(invested),
    value: Math.round(value),
    gain: Math.round(value - invested),
    gainPct: invested > 0 ? ((value - invested) / invested) * 100 : 0,
    monthlyContributions: Math.round(monthly),
    emergencyFund: Math.round(emergencyFund),
    byKind: [...byKind.entries()].map(([kind, v]) => ({ kind, value: Math.round(v) })).sort((a, b) => b.value - a.value),
  };
}

// ---------------------------------------------------------------------------
// Insurance
// ---------------------------------------------------------------------------

export const PAYMENTS_PER_YEAR: Record<PremiumFrequency, number> = {
  monthly: 12,
  quarterly: 4,
  half_yearly: 2,
  yearly: 1,
};

export const MONTHS_BETWEEN_PREMIUMS: Record<PremiumFrequency, number> = {
  monthly: 1,
  quarterly: 3,
  half_yearly: 6,
  yearly: 12,
};

export function annualPremium(p: Policy): number {
  return p.status === 'active' ? p.premium * PAYMENTS_PER_YEAR[p.frequency] : 0;
}

export function nextPremiumDateAfterPayment(p: Policy): string | undefined {
  return p.nextDueDate ? addMonthsToDate(p.nextDueDate, MONTHS_BETWEEN_PREMIUMS[p.frequency]) : undefined;
}

// ---------------------------------------------------------------------------
// Household summary
// ---------------------------------------------------------------------------

export interface Summary {
  /** Everything still owed across open liabilities. */
  outstanding: number;
  creditCardOutstanding: number;
  loanOutstanding: number;
  /** EMIs falling due each month across active plans + loans with an EMI. */
  monthlyEmi: number;
  /** Insurance premiums spread per month. */
  monthlyPremiums: number;
  /** Already repaid: paid installments + settled liabilities without a plan. */
  repaid: number;
  openCount: number;
  activePlanCount: number;
  closedCount: number;
  spentThisMonth: number;
  monthlyBudget: number;
  sumAssured: number;
  /** Last month any active plan has an unpaid installment. */
  debtFreeMonth?: string;
}

export function summarize(data: FinanceData, today: Date = new Date()): Summary {
  const byLiability = groupInstallments(data.installments);
  const thisMonth = toMonthKey(today);
  const s: Summary = {
    outstanding: 0,
    creditCardOutstanding: 0,
    loanOutstanding: 0,
    monthlyEmi: 0,
    monthlyPremiums: 0,
    repaid: 0,
    openCount: 0,
    activePlanCount: 0,
    closedCount: 0,
    spentThisMonth: 0,
    monthlyBudget: data.members.reduce((sum, m) => sum + (m.monthlyBudget || 0), 0),
    sumAssured: 0,
  };

  for (const l of data.liabilities) {
    const inst = byLiability.get(l.id) ?? [];
    const progress = planProgress(inst);
    s.repaid += progress.paidAmount;

    if (l.status === 'closed') {
      s.closedCount++;
      if (inst.length === 0) s.repaid += l.balance;
      continue;
    }

    const owed = outstandingFor(l, inst);
    s.outstanding += owed;
    s.openCount++;
    if (l.kind === 'credit_card' && l.status === 'active') s.creditCardOutstanding += owed;
    else s.loanOutstanding += owed;

    if (inst.length > 0 && progress.remainingAmount > 0) {
      s.activePlanCount++;
      s.monthlyEmi += progress.nextDue?.amount ?? l.emiAmount ?? 0;
      const lastUnpaid = inst.filter((i) => !i.paidOn).at(-1)?.dueMonth;
      if (lastUnpaid && (!s.debtFreeMonth || lastUnpaid > s.debtFreeMonth)) s.debtFreeMonth = lastUnpaid;
    }
  }

  for (const e of data.expenses) {
    if (e.date.startsWith(thisMonth)) s.spentThisMonth += e.amount;
  }
  for (const p of data.policies) {
    s.monthlyPremiums += annualPremium(p) / 12;
    if (p.status === 'active') s.sumAssured += p.sumAssured;
  }
  s.monthlyPremiums = Math.round(s.monthlyPremiums);
  return s;
}

// ---------------------------------------------------------------------------
// Upcoming payments — the "what do I need to pay, and when" list
// ---------------------------------------------------------------------------

export type DueItem =
  | { kind: 'installment'; key: string; date: string; days: number; amount: number; title: string; subtitle: string; memberId: string; liabilityId: string; installmentId: string }
  | { kind: 'card'; key: string; date: string; days: number; amount: number; title: string; subtitle: string; memberId: string; liabilityId: string }
  | { kind: 'premium'; key: string; date: string; days: number; amount: number; title: string; subtitle: string; memberId: string; policyId: string };

/** Installments are treated as due on the 5th unless the liability has a due day. */
export const DEFAULT_EMI_DAY = 5;

/**
 * Everything unpaid that is overdue or due within `horizonDays`, soonest first.
 * Only the earliest unpaid installment of each plan is listed, so a plan
 * never floods the list.
 */
export function upcomingPayments(data: FinanceData, todayIso: string, horizonDays = 30): DueItem[] {
  const items: DueItem[] = [];
  const byLiability = groupInstallments(data.installments);

  for (const l of data.liabilities) {
    if (l.status === 'closed') continue;
    const inst = byLiability.get(l.id) ?? [];
    const label = l.cardLast4 ? `${l.provider} ··${l.cardLast4}` : l.provider;

    if (inst.length > 0) {
      const next = planProgress(inst).nextDue;
      if (!next) continue;
      const date = dateInMonth(next.dueMonth, l.dueDay ?? DEFAULT_EMI_DAY);
      items.push({
        kind: 'installment',
        key: `i-${next.id}`,
        date,
        days: daysBetween(todayIso, date),
        amount: next.amount,
        title: label,
        subtitle: `EMI ${next.seq} of ${inst.length}`,
        memberId: l.memberId,
        liabilityId: l.id,
        installmentId: next.id,
      });
    } else if (l.kind === 'credit_card' && l.balance > 0 && l.dueDay) {
      const thisMonth = todayIso.slice(0, 7);
      let date = dateInMonth(thisMonth, l.dueDay);
      // A bill whose day has passed this month is shown for next month: we only
      // know the balance, not whether this month's statement was already paid.
      if (date < todayIso) date = dateInMonth(addMonthsToKey(thisMonth, 1), l.dueDay);
      items.push({
        kind: 'card',
        key: `c-${l.id}`,
        date,
        days: daysBetween(todayIso, date),
        amount: l.balance,
        title: label,
        subtitle: 'Card bill',
        memberId: l.memberId,
        liabilityId: l.id,
      });
    }
  }

  for (const p of data.policies) {
    if (p.status !== 'active' || !p.nextDueDate) continue;
    items.push({
      kind: 'premium',
      key: `p-${p.id}`,
      date: p.nextDueDate,
      days: daysBetween(todayIso, p.nextDueDate),
      amount: p.premium,
      title: p.name,
      subtitle: `${p.provider} premium`,
      memberId: p.memberId,
      policyId: p.id,
    });
  }

  return items
    .filter((i) => i.days <= horizonDays)
    .sort((a, b) => a.date.localeCompare(b.date) || b.amount - a.amount);
}

// ---------------------------------------------------------------------------
// Projections for charts
// ---------------------------------------------------------------------------

export interface MonthOutflow {
  month: string;
  emi: number;
  premiums: number;
}

/** Scheduled EMI + premium outflow for the next `months` months, starting this month. */
export function projectOutflow(data: FinanceData, today: Date, months = 12): MonthOutflow[] {
  const start = toMonthKey(today);
  const rows: MonthOutflow[] = Array.from({ length: months }, (_, i) => ({
    month: addMonthsToKey(start, i),
    emi: 0,
    premiums: 0,
  }));
  const index = new Map(rows.map((r, i) => [r.month, i]));
  const open = new Set(data.liabilities.filter((l) => l.status !== 'closed').map((l) => l.id));

  for (const i of data.installments) {
    if (i.paidOn || !open.has(i.liabilityId)) continue;
    // Overdue installments are still owed — count them in the current month
    const at = i.dueMonth < start ? 0 : index.get(i.dueMonth);
    if (at !== undefined) rows[at].emi += i.amount;
  }

  for (const p of data.policies) {
    if (p.status !== 'active' || !p.nextDueDate) continue;
    const step = MONTHS_BETWEEN_PREMIUMS[p.frequency];
    let due = p.nextDueDate.slice(0, 7);
    if (due < start) due = start;
    for (let k = 0; k < months; k += 1) {
      const at = index.get(due);
      if (at === undefined) break;
      rows[at].premiums += p.premium;
      due = addMonthsToKey(due, step);
    }
  }
  return rows;
}

/** Outstanding balance at the end of each of the next `months` months if every EMI is paid on schedule. */
export function projectBurndown(data: FinanceData, today: Date, months = 12) {
  const start = toMonthKey(today);
  const byLiability = groupInstallments(data.installments);
  let balance = 0;
  const scheduled: number[] = Array(months).fill(0);

  for (const l of data.liabilities) {
    const inst = byLiability.get(l.id) ?? [];
    balance += outstandingFor(l, inst);
    if (l.status === 'closed') continue;
    for (const i of inst) {
      if (i.paidOn) continue;
      const offset = i.dueMonth < start ? 0 : monthsBetween(start, i.dueMonth);
      if (offset < months) scheduled[offset] += i.amount;
    }
  }

  const rows = [{ month: start, balance }];
  let running = balance;
  for (let k = 0; k < months; k++) {
    running = Math.max(0, running - scheduled[k]);
    rows.push({ month: addMonthsToKey(start, k + 1), balance: running });
  }
  return rows;
}

function monthsBetween(from: string, to: string): number {
  const [fy, fm] = from.split('-').map(Number);
  const [ty, tm] = to.split('-').map(Number);
  return (ty - fy) * 12 + (tm - fm);
}

export function spendingByCategory(expenses: Expense[], monthKey: string) {
  const totals = new Map<string, number>();
  for (const e of expenses) {
    if (!e.date.startsWith(monthKey)) continue;
    totals.set(e.category, (totals.get(e.category) ?? 0) + e.amount);
  }
  return [...totals.entries()].map(([category, amount]) => ({ category, amount })).sort((a, b) => b.amount - a.amount);
}

export function memberById(members: Member[]): Map<string, Member> {
  return new Map(members.map((m) => [m.id, m]));
}

// ---------------------------------------------------------------------------
// Credit cards
// ---------------------------------------------------------------------------

export interface CardUsage {
  used: number;
  limit?: number;
  available?: number;
  /** 0–100+, undefined when the limit is unknown */
  percent?: number;
}

/** How much of a card's limit is in use. A converted balance still counts against the limit until repaid. */
export function cardUsage(l: Liability, installments: Installment[]): CardUsage {
  const used = outstandingFor(l, installments);
  if (!l.creditLimit || l.creditLimit <= 0) return { used };
  return {
    used,
    limit: l.creditLimit,
    available: Math.max(0, l.creditLimit - used),
    percent: (used / l.creditLimit) * 100,
  };
}

/** Credit utilisation bands used by Indian credit bureaus' guidance: under 30% is healthy. */
export function utilizationTone(percent: number): 'positive' | 'warning' | 'negative' {
  return percent <= 30 ? 'positive' : percent <= 75 ? 'warning' : 'negative';
}

export function isOpenCard(l: Liability): boolean {
  return l.kind === 'credit_card' && l.status !== 'closed';
}

/** Totals across cards that have a limit set. */
export function creditTotals(data: FinanceData) {
  const byLiability = groupInstallments(data.installments);
  let limit = 0;
  let used = 0;
  let cards = 0;
  for (const l of data.liabilities) {
    if (!isOpenCard(l) || !l.creditLimit) continue;
    cards++;
    limit += l.creditLimit;
    used += outstandingFor(l, byLiability.get(l.id) ?? []);
  }
  return { limit, used, cards, percent: limit > 0 ? (used / limit) * 100 : undefined };
}

// ---------------------------------------------------------------------------
// Overview helpers
// ---------------------------------------------------------------------------

export type DebtGroup = 'cards' | 'loans' | 'emis' | 'bnpl';

/** Outstanding split into what kind of debt it is. Converted card balances count as EMIs. */
export function debtMix(data: FinanceData): Record<DebtGroup, number> {
  const byLiability = groupInstallments(data.installments);
  const mix: Record<DebtGroup, number> = { cards: 0, loans: 0, emis: 0, bnpl: 0 };
  for (const l of data.liabilities) {
    const owed = outstandingFor(l, byLiability.get(l.id) ?? []);
    if (!owed) continue;
    const group: DebtGroup =
      l.kind === 'credit_card' ? (l.status === 'converted' ? 'emis' : 'cards') : l.kind === 'loan' ? 'loans' : l.kind === 'emi' ? 'emis' : 'bnpl';
    mix[group] += owed;
  }
  return mix;
}

/** EMIs falling due in a given month: how many and how much, and how much is already ticked off. */
export function monthEmiProgress(data: FinanceData, monthKey: string) {
  // Includes plans that were just closed, so finishing a plan this month shows as paid
  const known = new Set(data.liabilities.map((l) => l.id));
  let due = 0;
  let paid = 0;
  let count = 0;
  let paidCount = 0;
  for (const i of data.installments) {
    if (i.dueMonth !== monthKey || !known.has(i.liabilityId)) continue;
    count++;
    due += i.amount;
    if (i.paidOn) {
      paidCount++;
      paid += i.amount;
    }
  }
  return { due, paid, count, paidCount, percent: due > 0 ? (paid / due) * 100 : 0 };
}
